# Generated by Django 4.2.2 on 2023-06-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_profile',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
