# Generated by Django 4.2.2 on 2023-07-11 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='activity_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
