# Generated by Django 4.2.2 on 2022-07-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_activitylog_activity_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_priority',
            field=models.CharField(max_length=100),
        ),
    ]
