# Generated by Django 4.2.2 on 2023-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_updates_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default='01-01-1999', upload_to='news-images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='announcement_image',
            field=models.ImageField(default='01-01-1999', upload_to='announcement-images'),
            preserve_default=False,
        ),
    ]
