# Generated by Django 4.2.3 on 2023-07-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default='1999-01-01'),
            preserve_default=False,
        ),
    ]
