# Generated by Django 4.2.3 on 2023-07-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_notification_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeactivatedTask',
        ),
    ]
