# Generated by Django 4.2.3 on 2023-08-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_project_duration_alter_project_estimated_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_hours',
            field=models.TextField(),
        ),
    ]
