# Generated by Django 4.2.3 on 2023-08-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_project_duration_alter_project_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='home.project'),
            preserve_default=False,
        ),
    ]
