# Generated by Django 4.2.3 on 2023-08-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_taskattachment_todo_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='attachments',
        ),
    ]
