# Generated by Django 4.2.3 on 2023-08-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_list_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='attachment_title',
            field=models.CharField(default='attachment', max_length=256),
            preserve_default=False,
        ),
    ]
