# Generated by Django 4.2.3 on 2023-08-14 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0028_alter_issueattachment_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assignee',
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='assignee',
            field=models.ManyToManyField(through='home.ProjectTeam', to=settings.AUTH_USER_MODEL),
        ),
    ]
